2021~2030년 자동차 온실가스·연비 기준 행정예고에 따르면 구 환경부는 2021-2030년 사이에 10인 이하 승용·승합차의 연비를

In [2]:
33.1 / 24.3

1.3621399176954734

36.2% 개선하고, 승합(11～15인)·소형화물의 연비를

In [3]:
17.3 / 15.2

1.1381578947368423

13.8% 개선

# Current Policy

* Car에 대해서 5년마다

In [1]:
import numpy as np

In [2]:
np.exp((np.log(33.1 / 24.3)) / 2)

1.1671075004880542

연비 16.7% 상승

In [3]:
# Car
coef_2020 = 2449.0917851
eff_imp = 0.007
coef_2025 = coef_2020 * (1-eff_imp) ** 5
coef_2030 = coef_2025 * (1-eff_imp) ** 5
coef_2035 = coef_2030 * (1-eff_imp) ** 5
coef_2025, coef_2030, coef_2035

(2364.565256571561, 2282.956027455311, 2204.1634117771714)

In [6]:
eff_imp_ep = 0.02
coef_2030_ep = coef_2025 * (1-eff_imp_ep)  ** 5
coef_2035_ep = coef_2030_ep * (1-eff_imp_ep)  ** 5
coef_2030_ep, coef_2035_ep

(2137.3797108057615, 1932.0219712556973)

In [58]:
((48.74 / 35.95) ** (1/8)) ** (15)

1.769497410786113

In [43]:
# Car
coef_2020 = 2449.0917851
eff_imp = 0.167
coef_2025 = coef_2020 * (1-eff_imp)
coef_2030 = coef_2025 * (1-eff_imp)
coef_2035 = coef_2030 * (1-eff_imp)
coef_2025, coef_2030, coef_2035

(2040.0934569882997, 1699.3978496712537, 1415.5984087761542)

Large Car and Truck에 대해서 5년마다

In [67]:
import numpy as np

In [68]:
np.exp((np.log(17.3 / 15.2)) / 2) ** (1/5)

1.013025205879472

6.7% 상승

In [ ]:
# Large Car and Truck
coef_2020 = 1039.9009244
eff_imp = 0.067
coef_2025 = coef_2020 * (1-eff_imp)
coef_2030 = coef_2025 * (1-eff_imp)
coef_2035 = coef_2030 * (1-eff_imp)
coef_2025, coef_2030, coef_2035

In [11]:
# Large Car and Truck
coef_2020 = 1039.9009244
eff_imp = 0.067
coef_2025 = coef_2020 * (1-eff_imp)
coef_2030 = coef_2025 * (1-eff_imp)
coef_2035 = coef_2030 * (1-eff_imp)
coef_2025, coef_2030, coef_2035

(970.2275624652, 905.2223157800316, 844.5724206227695)

# Enhanced Policy

* Car: 2025년 이후부터는 5년 평균 33% 개선
* Large Car and Truck: 2025년 이후부터는 연평균 13% 개선
* Bus & Medium Truck: 2025년 이후 5년마다

In [12]:
np.exp((np.log(17.3 / 15.2)) / 2)

1.066844831611815

6.7% 개선

In [13]:
# Car
coef_2020 = 2449.0917851
eff_imp = 0.167
coef_2025 = coef_2020 * (1-eff_imp)
eff_imp_ep = 0.33
coef_2030 = coef_2025 * (1-eff_imp_ep)
coef_2035 = coef_2030 * (1-eff_imp_ep)
coef_2025, coef_2030, coef_2035

(2040.0934569882997, 1366.8626161821608, 915.7979528420476)

In [14]:
# Large Car and Truck
coef_2020 = 1039.9009244
eff_imp = 0.067
coef_2025 = coef_2020 * (1-eff_imp)
eff_imp_ep = 0.13
coef_2030 = coef_2025 * (1-eff_imp_ep)
coef_2035 = coef_2030 * (1-eff_imp_ep)
coef_2025, coef_2030, coef_2035

(970.2275624652, 844.097979344724, 734.3652420299098)

In [17]:
# Bus
coef_2025 = 4999.5868604
eff_imp = 0.067
coef_2030 = coef_2025 * (1-eff_imp)
coef_2035 = coef_2030 * (1-eff_imp)
coef_2025, coef_2030, coef_2035

(4999.5868604, 4664.6145407532, 4352.085366522736)

In [18]:
# Medium Truck
coef_2025 = 1370.1064312
eff_imp = 0.067
coef_2030 = coef_2025 * (1-eff_imp)
coef_2035 = coef_2030 * (1-eff_imp)
coef_2025, coef_2030, coef_2035

(1370.1064312, 1278.3093003096, 1192.6625771888569)

In [1]:
import pandas as pd

In [4]:
df = pd.read_excel("../resources/자동차표시연비 목록.xlsx")
df

,업체명,모델명,연료,변속형식,차량형식,자동차 종류,표시연비,도심주행연비,고속도로연비,CO2배출량(g/km),1회충전주행거리(km),배기량,등급,출시연도,예상 연간유류비
0,아우디,Q6 e-tron performance,전기,없음,전기,승용차,4.3,4.6,3.9,NaN,447.0,NaN,3등급,2026,1339221.0
1,현대,G80(RG3) FL 3.5T-GDI AWD 8AT 5인 19인치 빌트인캠 통합(2...,휘발유,자동,내연기관,승용차,8.2,7.1,10.2,209.0,NaN,3470.0,5등급,2026,3012274.0
2,현대,G80(RG3) FL 3.5T-GDI RWD 8AT 5인 19인치 빌트인캠 통합(2...,휘발유,자동,내연기관,승용차,8.8,7.6,11.0,193.0,NaN,3470.0,5등급,2026,2806892.0
3,벤츠,Mercedes-Maybach EQS 680 SUV,전기,없음,전기,승용차,3.4,3.4,3.4,NaN,464.0,NaN,4등급,2025,1693721.0
4,Lotus,Emeya R,전기,없음,전기,승용차,3.2,3.0,3.3,NaN,374.0,NaN,5등급,2025,1799578.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3945,파워테크닉스,EV SAVER(파워테크닉스 세이버 KNCSZ76ADK803665),전기,없음,전기,승용차,1.6,1.6,1.7,NaN,64.0,NaN,5등급,2015,3599156.0
3946,현대,아슬란 3.0GDI,휘발유,자동,내연기관,승용차,9.5,8.1,11.8,188.0,NaN,2999.0,4등급,2014,2600068.0
3947,현대,아슬란 3.3GDI,휘발유,자동,내연기관,승용차,9.5,8.1,11.9,188.0,NaN,3342.0,4등급,2014,2600068.0
3948,AD모터스,Change,전기,없음,전기,승용차,4.3,4.3,0.0,NaN,27.0,0.0,초소형,2012,1339221.0
3949,닛산,인피니티 FX35,휘발유,자동,내연기관,승용차,7.9,NaN,NaN,297.0,NaN,3498.0,5등급,2008,3126665.0

In [28]:
df['배기량'].unique()

array([  nan, 3470., 1598., 3342., 3497., 2992., 3996., 3982., 2497.,
       2487., 2727., 2494., 1999., 2993., 2998., 6498., 6496., 1991.,
       4395.,  998., 1995., 2261., 1998., 1969., 1984., 1199., 3591.,
       3994., 1498., 1968., 2995., 2480., 2997., 6749., 3445., 1997.,
       6162., 5204., 3471., 2989., 1993., 2956., 2996., 2151., 3456.,
       2894., 5980., 1950., 1499., 1987., 2393., 2157., 1497., 2967.,
       1332., 2999., 3604., 2469., 3990., 3855., 5038., 1580., 2199.,
       3778., 2726., 1591., 1996., 2981., 3745., 2925., 1490., 1341.,
       3496., 3564., 5035., 3339., 2387., 2360., 2299., 2694., 2959.,
       3649., 2979., 1597., 3799., 4969., 3995., 1399., 1493., 1798.,
       2359.,  999., 5461., 3498., 2488., 1796., 1240., 1582., 1368.,
       2987., 1353., 2143., 1362.,  796., 2776.,    0.])

In [51]:
df[(df['업체명'] == '현대') & (df['차량형식'] == '내연기관') & (df['연료'] == '휘발유') & (df['자동차 종류'] == '승용차') & (df['배기량'] >= 2000) & (df['배기량'] <=3000)]['모델명'].unique()

array(['G70(IK PE2) 2.5T-GDI AWD 18인치 (26MY)',
       'G70(IK PE2) 2.5T-GDI AWD 18인치(빌트인캠) (26MY)',
       'G70(IK PE2) 2.5T-GDI S/B 2WD 18인치 (26MY)',
       'G70(IK PE2) 2.5T-GDI S/B 2WD 18인치(빌트인캠) (26MY)',
       'G70(IK PE2) 2.5T-GDI S/B 2WD 19인치(올시즌) (26MY)',
       'G70(IK PE2) 2.5T-GDI S/B 2WD 19인치(썸머) (26MY)',
       'G70(IK PE2) 2.5T-GDI S/B AWD 18인치 (26MY)',
       'G70(IK PE2) 2.5T-GDI S/B AWD 18인치(빌트인캠) (26MY)',
       'G70(IK PE2) 2.5T-GDI S/B AWD 19인치(올시즌) (26MY)',
       'G70(IK PE2) 2.5T-GDI S/B AWD 19인치(썸머) (26MY)',
       'G70(IK PE2) 2.5T-GDI 2WD 18인치 (26MY)',
       'G70(IK PE2) 2.5T-GDI 2WD 18인치(빌트인캠) (26MY)',
       'G70(IK PE2) 2.5T-GDI 2WD 19인치(올시즌) (26MY)',
       'G70(IK PE2) 2.5T-GDI 2WD 19인치(썸머) (26MY)',
       'G70(IK PE2) 2.5T-GDI AWD 19인치(올시즌) (26MY)',
       'G70(IK PE2) 2.5T-GDI AWD 19인치(썸머) (26MY)',
       'GV70(JK1) FL 2.5T-GDI AWD 19인치 빌트인캠 통합 스포츠패키지(26MY)',
       'GV70(JK1) FL 2.5T-GDI RWD 19인치 빌트인캠 통합 스포츠패키지(26MY)',
       'G80(RG3) FL 2.5T-GDI RWD 20인치 26MY',
       'G80(RG3) FL 2.5T-GDI AWD 20인치 26MY',
       '팰리세이드(LX3) 2.5T-GDI 2WD 8AT 7인 20인치',
       '팰리세이드(LX3) 2.5T-GDI 2WD 8AT 7인 21인치',
       '팰리세이드(LX3) 2.5T-GDI AWD 8AT 9인 20인치',
       '팰리세이드(LX3) 2.5T-GDI AWD 8AT 9인 21인치',
       '팰리세이드(LX3) 2.5T-GDI AWD 8AT 7인 20인치',
       '팰리세이드(LX3) 2.5T-GDI 2WD 8AT 7인 18인치 빌트인캠 유',
       '팰리세이드(LX3) 2.5T-GDI 2WD 8AT 7인 18인치 빌트인캠 무',
       '팰리세이드(LX3) 2.5T-GDI AWD 8AT 9인 18인치',
       '팰리세이드(LX3) 2.5T-GDI AWD 8AT 7인 18인치',
       '팰리세이드(LX3) 2.5T-GDI 2WD 8AT 9인 20인치',
       '팰리세이드(LX3) 2.5T-GDI 2WD 8AT 9인 18인치 빌트인캠 유',
       '팰리세이드(LX3) 2.5T-GDI 2WD 8AT 9인 18인치 빌트인캠 무',
       '팰리세이드(LX3) 2.5T-GDI 2WD 8AT 9인 21인치',
       '팰리세이드(LX3) 2.5T-GDI AWD 8AT 7인 21인치',
       'G80(RG3) FL 2.5T-GDI AWD 18인치 빌트인캠 무 26MY',
       'G80(RG3) FL 2.5T-GDI AWD 18인치 빌트인캠 유 26MY',
       'G80(RG3) FL 2.5T-GDI AWD 20인치 26MY(올시즌)',
       'G80(RG3) FL 2.5T-GDI AWD 19인치 26MY',
       'G80(RG3) FL 2.5T-GDI RWD 20인치 26MY(올시즌)',
       'G80(RG3) FL 2.5T-GDI RWD 19인치 26MY',
       'G80(RG3) FL 2.5T-GDI RWD 18인치 빌트인캠 무 26MY',
       'G80(RG3) FL 2.5T-GDI RWD 18인치 빌트인캠 유 26MY',
       'GV80 개조 2.5T AWD 쿠페 (25MY)', 'GV80 개조 2.5T AWD 20"/22" (25MY)',
       'GV80 개조 2.5T AWD 19" 6/7인 (25MY)',
       'GV80 개조 2.5T AWD 19" 5인 빌트인캠 장착 (25MY)',
       'GV80 개조 2.5T AWD 19" 5인 빌트인캠 미장착 (25MY)',
       'G80(PE) 2.5T-GDI RWD 20"', 'G80(PE) 2.5T-GDI AWD 20"',
       'GV70 FL 2.5T-GDI AWD 21"', 'GV70 FL 2.5T-GDI AWD 19"',
       'GV70 FL 2.5T-GDI RWD 18"(C)', 'GV70 FL 2.5T-GDI RWD 18"(nC)',
       'GV70 FL 2.5T-GDI AWD 19" 스포츠패키지',
       'GV70 FL 2.5T-GDI AWD 21" 스포츠패키지', 'GV70 FL 2.5T-GDI RWD 21"',
       'GV70 FL 2.5T-GDI RWD 19"', 'GV70 FL 2.5T-GDI AWD 18"',
       'GV70 FL 2.5T-GDI RWD 21" 스포츠패키지',
       'GV70 FL 2.5T-GDI RWD 19" 스포츠패키지', 'G80(PE) 2.5T-GDI RWD 20"(올시즌)',
       'G80(PE) 2.5T-GDI RWD 20"(썸머)', 'G80(PE) 2.5T-GDI RWD 19"',
       'G80(PE) 2.5T-GDI RWD 18" (nC)', 'G80(PE) 2.5T-GDI RWD 18" (C)',
       'G80(PE) 2.5T-GDI AWD 20"(올시즌)', 'G80(PE) 2.5T-GDI AWD 20"(썸머)',
       'G80(PE) 2.5T-GDI AWD 19"', 'G80(PE) 2.5T-GDI AWD 18" (nC)',
       'G80(PE) 2.5T-GDI AWD 18" (C)', 'GV80 개조 2.5T AWD 쿠페',
       'GV80 개조 2.5T 2WD 19" 빌트인캠 장착', 'GV80 개조 2.5T 2WD 19" 빌트인캠 미장착',
       'GV80 개조 2.5T 2WD 20"/22"', 'GV80 개조 2.5T AWD 20"/22"',
       'GV80 개조 2.5T AWD 19" 6/7인', 'GV80 개조 2.5T AWD 19" 5인 빌트인캠 장착',
       'GV80 개조 2.5T AWD 19" 5인 빌트인캠 미장착',
       '싼타페(MX5) 2.5T-GDI 2WD 6/7인 20인치타이어',
       '싼타페(MX5) 2.5T-GDI AWD 7인 20인치타이어',
       '싼타페(MX5) 2.5T-GDI AWD 5/6인 20인치타이어',
       '싼타페(MX5) 2.5T-GDI 2WD 7인 18인치(빌트인캠)',
       '싼타페(MX5) 2.5T-GDI 2WD 5/6/7인 21인치타이어',
       '싼타페(MX5) 2.5T-GDI 2WD 5인 20인치타이어',
       '싼타페(MX5) 2.5T-GDI 2WD 7인 18인치타이어',
       '싼타페(MX5) 2.5T-GDI 2WD 5/6인 18인치(빌트인캠)',
       '싼타페(MX5) 2.5T-GDI 2WD 5/6인 18인치타이어',
       '싼타페(MX5) 2.5T-GDI AWD 6/7인 21인치타이어',
       '싼타페(MX5) 2.5T-GDI AWD 5인 21인치타이어',
       '싼타페(MX5) 2.5T-GDI AWD 5/6/7인 18인치타이어',
       'GV70 2.5T-GDI AWD 21인치(24MY)',
       'GV70 2.5T-GDI AWD 21인치 (스포츠패키지)(24MY)',
       'GV70 2.5T-GDI AWD 19인치(24MY)',
       'GV70 2.5T-GDI AWD 19인치 (스포츠패키지)(24MY)',
       'GV70 2.5T-GDI AWD 18인치(빌트인캠)(24MY)',
       'GV70 2.5T-GDI AWD 18인치(24MY)', 'GV70 2.5T-GDI 2WD 21인치(24MY)',
       'GV70 2.5T-GDI 2WD 21인치 (스포츠패키지)(24MY)',
       'GV70 2.5T-GDI 2WD 19인치(24MY)',
       'GV70 2.5T-GDI 2WD 19인치 (스포츠패키지)(24MY)',
       'GV70 2.5T-GDI 2WD 18인치(빌트인캠)(24MY)',
       'GV70 2.5T-GDI 2WD 18인치(24MY)',
       'G70(IK PE2) 2.5T-GDI S/B AWD 19인치(썸머)',
       'G70(IK PE2) 2.5T-GDI S/B AWD 19인치(올시즌)',
       'G70(IK PE2) 2.5T-GDI S/B AWD 18인치(빌트인캠)',
       'G70(IK PE2) 2.5T-GDI S/B AWD 18인치',
       'G70(IK PE2) 2.5T-GDI S/B 2WD 19인치(썸머)',
       'G70(IK PE2) 2.5T-GDI S/B 2WD 19인치(올시즌)',
       'G70(IK PE2) 2.5T-GDI S/B 2WD 18인치(빌트인캠)',
       'G70(IK PE2) 2.5T-GDI S/B 2WD 18인치',
       'G70(IK PE2) 2.5T-GDI AWD 19인치(썸머)',
       'G70(IK PE2) 2.5T-GDI 2WD 19인치(올시즌)',
       'G70(IK PE2) 2.5T-GDI AWD 18인치(빌트인캠)',
       'G70(IK PE2) 2.5T-GDI 2WD 18인치',
       'G70(IK PE2) 2.5T-GDI 2WD 19인치(썸머)',
       'G70(IK PE2) 2.5T-GDI AWD 19인치(올시즌)',
       'G70(IK PE2) 2.5T-GDI 2WD 18인치(빌트인캠)',
       'G70(IK PE2) 2.5T-GDI AWD 18인치', '쏘나타(DN8) 개조 2.5 T-GDI_19인치타이어',
       '그랜저(GN7) 2.5 GDI 20인치', '그랜저(GN7) 2.5 GDI 19인치',
       '그랜저(GN7) 2.5 GDI 18인치', '싼타페(개조) 2.5T-GDI AWD 6인 20인치(22MY)',
       '싼타페(개조) 2.5T-GDI AWD 6인 18인치(22MY)',
       '싼타페(개조) 2.5T-GDI 2WD 6인 20인치(22MY)',
       '싼타페(개조)2.5T-GDI 2WD 6인 18인치(빌트인캠)_22MY',
       '싼타페(개조) 2.5T-GDI 2WD 6인 18인치(22MY)',
       'GV80(22MY) 2.5T-GDI AWD 5인 20인치타이어',
       'GV80(22MY) 2.5T-GDI AWD 5인 22인치타이어',
       'GV80(22MY) 2.5T-GDI AWD 5인 19인치타이어(빌트인캠)',
       'GV80(22MY) 2.5T-GDI AWD 6인 19인치타이어(빌트인캠)',
       'GV80(22MY) 2.5T-GDI AWD 7인 19인치타이어(빌트인캠)',
       'GV80(22MY) 2.5T-GDI AWD 5인 19인치타이어',
       'GV80(22MY) 2.5T-GDI AWD 6인 19인치타이어',
       'GV80(22MY) 2.5T-GDI AWD 7인 19인치타이어',
       'GV80(22MY) 2.5T-GDI AWD 6인 20인치타이어',
       'GV80(22MY) 2.5T-GDI AWD 6인 22인치타이어',
       'GV80(22MY) 2.5T-GDI AWD 7인 20인치타이어',
       'GV80(22MY) 2.5T-GDI AWD 7인 22인치타이어',
       'GV80(22MY) 2.5T-GDI 2WD 5인승 19인치 타이어',
       'GV80(22MY) 2.5T-GDI 2WD 5인 19인치타이어(빌트인캠)',
       'GV80(22MY) 2.5T-GDI 2WD 6인 19인치타이어',
       'GV80(22MY) 2.5T-GDI 2WD 7인 19인치타이어',
       'GV80(22MY) 2.5T-GDI 2WD 5인 20인치타이어',
       'GV80(22MY) 2.5T-GDI 2WD 5인 22인치타이어',
       'GV80(22MY) 2.5T-GDI 2WD 6인 20인치타이어',
       'GV80(22MY) 2.5T-GDI 2WD 6인 22인치타이어',
       'GV80(22MY) 2.5T-GDI 2WD 7인 20인치타이어',
       'GV80(22MY) 2.5T-GDI 2WD 7인 22인치타이어', 'G80 2.5T-GDI AWD 20인치 (SP)',
       'G80 2.5T-GDI AWD 20인치 (22MY)', 'G80 2.5T-GDI AWD 19인치 (SP)',
       'G80 2.5T-GDI 2WD 20인치 (SP)', 'G80 2.5T-GDI 2WD 20인치 (22MY)',
       'G80 2.5T-GDI 2WD 19인치 (SP)', 'GV70 2.5T-GDI AWD 21인치',
       'GV70 2.5T-GDI AWD 19인치', 'GV70 2.5T-GDI 2WD 21인치',
       'GV70 2.5T-GDI 2WD 19인치', 'GV70 2.5T-GDI AWD 21인치 (스포츠패키지)',
       'GV70 2.5T-GDI AWD 19인치 (스포츠패키지)', 'GV70 2.5T-GDI AWD 18인치(빌트인캠)',
       'GV70 2.5T-GDI AWD 18인치', 'GV70 2.5T-GDI 2WD 21인치 (스포츠패키지)',
       'GV70 2.5T-GDI 2WD 19인치 (스포츠패키지)', 'GV70 2.5T-GDI 2WD 18인치(빌트인캠)',
       'GV70 2.5T-GDI 2WD 18인치', '싼타페(개조) 2.5T-GDI AWD 5인 20인치타이어',
       '싼타페(개조) 2.5T-GDI AWD 5인 18인치타이어',
       '싼타페(개조) 2.5T-GDI 2WD 5인 20인치타이어',
       '싼타페(개조) 2.5T-GDI AWD 7인 20인치타이어',
       '싼타페(개조) 2.5T-GDI AWD 7인 18인치타이어',
       '싼타페(개조) 2.5T-GDI 2WD 7인 20인치타이어',
       '싼타페(개조) 2.5T-GDI 2WD 7인 18인치(빌트인캠)',
       '싼타페(개조) 2.5T-GDI 2WD 7인 18인치타이어',
       '싼타페(개조) 2.5T-GDI 2WD 5인 18인치(빌트인캠)',
       '싼타페(개조) 2.5T-GDI 2WD 5인 18인치타이어',
       '쏘나타(DN8) 2.5 T-GDI_19인치타이어(빌트인캠)', '쏘나타(DN8) 2.5 T-GDI_19인치타이어',
       'GV80 2.5T-GDI AWD 5인 19인치타이어 (빌트인캠)',
       'GV80 2.5T-GDI AWD 5인 19인치타이어', 'GV80 2.5T-GDI AWD 5인 20인치타이어',
       'GV80 2.5T-GDI AWD 7인 20인치타이어', 'GV80 2.5T-GDI 2WD 5인 22인치타이어',
       'GV80 2.5T-GDI 2WD 5인 20인치타이어', 'GV80 2.5T-GDI 2WD 7인 20인치타이어',
       'GV80 2.5T-GDI AWD 7인 22인치타이어',
       'GV80 2.5T-GDI AWD 7인 19인치타이어 (빌트인캠)',
       'GV80 2.5T-GDI AWD 7인 19인치타이어', 'GV80 2.5T-GDI AWD 5인 22인치타이어',
       'GV80 2.5T-GDI 2WD 7인 22인치타이어', 'GV80 2.5T-GDI 2WD 7인 19인치타이어',
       'GV80 2.5T-GDI 2WD 5인 19인치타이어 (빌트인캠)',
       'GV80 2.5T-GDI 2WD 5인승 19인치 타이어', 'G80 2.5T-GDI AWD 20인치타이어',
       'G80 2.5T-GDI AWD 19인치타이어', 'G80 2.5T-GDI AWD 18인치 (빌트인캠)',
       'G80 2.5T-GDI AWD 18인치타이어', 'G80 2.5T-GDI 2WD 20인치타이어',
       'G80 2.5T-GDI 2WD 19인치타이어', 'G80 2.5T-GDI 2WD 18인치 (빌트인캠)',
       'G80 2.5T-GDI 2WD 18인치타이어', '그랜저(IG개조) 2.5 GDI_19인치타이어',
       '그랜저(IG개조) 2.5 GDI_18인치타이어', '그랜저(IG개조) 2.5 GDI_17인치타이어',
       '그랜저 3.0GDI 8AT (19"타이어) (15)', '그랜저 3.0GDI 8AT (18"타이어) (15)',
       '그랜저 2.4GDI (19"타이어) (15)', '그랜저 2.4GDI (18"타이어) (15)',
       '그랜저 2.4GDI (17"타이어) (15)', '아슬란 3.0GDI 8AT (19"타이어) (15)',
       '아슬란 3.0GDI 8AT (18"타이어) (15)', '아슬란 3.0GDI'], dtype=object)

In [49]:
df[(df['업체명'] == '현대') & (df['차량형식'] == '내연기관') & (df['연료'] == '휘발유') & (df['자동차 종류'] == '승용차') & (df['배기량'] >= 2000) & (df['배기량'] <=3000)].groupby(['출시연도', '연료', '자동차 종류'])['표시연비'].mean().reset_index()

   출시연도   연료 자동차 종류       표시연비
0  2014  휘발유    승용차   9.500000
1  2016  휘발유    승용차  10.385714
2  2019  휘발유    승용차  11.533333
3  2020  휘발유    승용차   9.759574
4  2021  휘발유    승용차   9.207143
5  2022  휘발유    승용차  10.587500
6  2023  휘발유    승용차   9.971429
7  2024  휘발유    승용차   9.546429
8  2025  휘발유    승용차   9.730952

In [40]:
((10.270370 / 8.571429) ** (1/10)) ** 5

1.094627687126013

In [24]:
df[(df['차량형식'] == '내연기관') & (df['연료'] == '경유') & (df['자동차 종류'] == '화물차')].groupby(['출시연도', '연료', '자동차 종류'])['표시연비'].mean().reset_index()

   출시연도  연료 자동차 종류       표시연비
0  2015  경유    화물차   9.000000
1  2016  경유    화물차   9.020588
2  2017  경유    화물차  10.150000
3  2019  경유    화물차   9.781081
4  2020  경유    화물차  11.000000
5  2021  경유    화물차  10.862500
6  2022  경유    화물차   9.740541
7  2023  경유    화물차  10.066667
8  2025  경유    화물차  10.225000

In [44]:
((11.000000 / 10.225000) ** (1/5)) ** 5

1.0757946210268945