# Source

* Data Source:
    * Administrative Notice on Average Greenhouse Gas and Fuel Economy Standards for Automobiles (2021–2030), Ministry of Environment. (`../resources/NFES-2020-MOE`)

* Implemented Input Files
    * `/input/policy/korea-2035/transportation/CAFE_cp.xml`
    * `/input/policy/korea-2035/transportation/CAFE_ep.xml`

# Fuel Economy Standard

According to the Administrative Notice on Average Greenhouse Gas Emission and Fuel Economy Standards for Automobiles (2021–2030), Ministry of Environment, Korea’s passenger cars are required to improve fuel economy by 30% by 2030 relative to 2020 levels. In the *Enhanced Ambition* scenario, we assume a 45% improvement by 2035. For freight trucks, we assume a 30% improvement from 2025 to 2035. To maintain consistency with the model, the fuel economy improvement rates were applied to GCAM’s default values to create the input file.

In [2]:
import pandas as pd

In [44]:
df = pd.read_csv("../../input/gcamdata/inst/extdata/energy/UCD_trn_data_CORE.csv", skiprows=5)
df.head()

,UCD_region,UCD_sector,mode,size.class,UCD_technology,UCD_fuel,variable,unit,2005,2010,...,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100
0,Africa,Passenger,LDV_2W,Motorcycle (50-250cc),All,All,annual travel per vehicle,vkt/veh/yr,8478.0,8478.0,...,8478.0,8478.0,8478.0,8478.0,8478.0,8478.0,8478.0,8478.0,8478.0,8478.0
1,Africa,Passenger,LDV_3W,Three-Wheeler,All,All,annual travel per vehicle,vkt/veh/yr,8478.0,8478.0,...,8478.0,8478.0,8478.0,8478.0,8478.0,8478.0,8478.0,8478.0,8478.0,8478.0
2,Africa,Passenger,LDV_4W,Mini Car,All,All,annual travel per vehicle,vkt/veh/yr,10391.0,10391.0,...,10391.0,10391.0,10391.0,10391.0,10391.0,10391.0,10391.0,10391.0,10391.0,10391.0
3,Africa,Passenger,LDV_4W,Subcompact Car,All,All,annual travel per vehicle,vkt/veh/yr,10391.0,10391.0,...,10391.0,10391.0,10391.0,10391.0,10391.0,10391.0,10391.0,10391.0,10391.0,10391.0
4,Africa,Passenger,LDV_4W,Compact Car,All,All,annual travel per vehicle,vkt/veh/yr,10391.0,10391.0,...,10391.0,10391.0,10391.0,10391.0,10391.0,10391.0,10391.0,10391.0,10391.0,10391.0

In [45]:
df.columns

Index(['UCD_region', 'UCD_sector', 'mode', 'size.class', 'UCD_technology',
       'UCD_fuel', 'variable', 'unit', '2005', '2010', '2015', '2020', '2025',
       '2030', '2035', '2040', '2045', '2050', '2055', '2060', '2065', '2070',
       '2075', '2080', '2085', '2090', '2095', '2100'],
      dtype='object')

In [46]:
df['mode'].unique()

array(['LDV_2W', 'LDV_3W', 'LDV_4W', 'Air Domestic', 'Air International',
       'Bus', 'HSR', 'Rail', 'Ship Domestic', 'Ship International',
       'Truck', 'Walk', 'Cycle'], dtype=object)

In [49]:
dfSub = df[(df['UCD_region'] == 'Korea') & (df['variable'] == 'intensity') & (df['mode'] == 'LDV_4W') & (df['size.class'] == 'Compact Car')].copy()
dfSub[["UCD_sector","size.class","UCD_technology", "UCD_fuel", 'variable', 'unit', '2020', '2030']]

,UCD_sector,size.class,UCD_technology,UCD_fuel,variable,unit,2020,2030
2282,Passenger,Compact Car,Liquids,Liquids,intensity,MJ/vkm,2.4472,2.284000
2283,Passenger,Compact Car,Hybrid Liquids,Liquids,intensity,MJ/vkm,1.9010,1.807533
2284,Passenger,Compact Car,NG,Natural Gas,intensity,MJ/vkm,2.4822,2.323733
2285,Passenger,Compact Car,BEV,Electricity,intensity,MJ/vkm,0.7258,0.720733
2286,Passenger,Compact Car,FCEV,Hydrogen,intensity,MJ/vkm,1.0928,1.055133

In [51]:
0.99 *2.4472 + 0.01 * 0.7258

2.4299860000000004

In [55]:
((1/3) * 2.284000 + (1/3) * 1.807533 + (2/9) * 0.720733 + (1/9) * 1.055133) / (0.99 *2.4472 + 0.01 * 0.7258)

0.6754130362159378

In [ ]:
dfSub = df[(df['UCD_region'] == 'Korea') & (df['variable'] == 'intensity')].copy()
dfSub[["UCD_sector","size.class","UCD_technology", "UCD_fuel", 'variable', 'unit', '2020', '2030']]

Empty DataFrame
Columns: [UCD_sector, size.class, UCD_technology, UCD_fuel, variable, unit, 2020, 2030]
Index: []

In [41]:
T=15
dfSub["rate_2020_2035"] = 1 - (dfSub['2035']/dfSub['2020'])**(1/T)
out = dfSub[["UCD_sector","size.class","UCD_technology","UCD_fuel","rate_2020_2035"]]
out

,UCD_sector,size.class,UCD_technology,UCD_fuel,rate_2020_2035
2277,Passenger,Subcompact Car,Liquids,Liquids,0.007000
2278,Passenger,Subcompact Car,Hybrid Liquids,Liquids,0.005094
2279,Passenger,Subcompact Car,NG,Natural Gas,0.006686
2280,Passenger,Subcompact Car,BEV,Electricity,0.000697
2281,Passenger,Subcompact Car,FCEV,Hydrogen,0.003531
2282,Passenger,Compact Car,Liquids,Liquids,0.007002
2283,Passenger,Compact Car,Hybrid Liquids,Liquids,0.005094
2284,Passenger,Compact Car,NG,Natural Gas,0.006688
2285,Passenger,Compact Car,BEV,Electricity,0.000702
2286,Passenger,Compact Car,FCEV,Hydrogen,0.003533
2287,Passenger,Large Car,Liquids,Liquids,0.006999
2288,Passenger,Large Car,Hybrid Liquids,Liquids,0.005095
2289,Passenger,Large Car,NG,Natural Gas,0.006687
2290,Passenger,Large Car,BEV,Electricity,0.000691
2291,Passenger,Large Car,FCEV,Hydrogen,0.003535
2292,Passenger,Light Truck and SUV,Liquids,Liquids,0.007000
2293,Passenger,Light Truck and SUV,Hybrid Liquids,Liquids,0.005094
2294,Passenger,Light Truck and SUV,NG,Natural Gas,0.006685
2295,Passenger,Light Truck and SUV,BEV,Electricity,0.000696
2296,Passenger,Light Truck and SUV,FCEV,Hydrogen,0.003535

In [39]:
out.groupby(['UCD_fuel'])['rate_2020_2035'].mean()

UCD_fuel
Electricity    0.000696
Hydrogen       0.003534
Liquids        0.006047
Natural Gas    0.006687
Name: rate_2020_2035, dtype: float64

In [60]:
dfSub = df[(df['UCD_region'] == 'Korea') & (df['variable'] == 'intensity') & (df['mode'] == 'Truck')].copy()
dfSub

,UCD_region,UCD_sector,mode,size.class,UCD_technology,UCD_fuel,variable,unit,2005,2010,...,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100
2303,Korea,Freight,Truck,Truck,Liquids,Liquids,intensity,MJ/vkm,1.5196,1.500933,...,1.341033,1.324367,1.3077,1.291633,1.275567,1.2595,1.244033,1.228567,1.2131,1.2131
2304,Korea,Freight,Truck,Truck,NG,Natural Gas,intensity,MJ/vkm,1.8235,1.801100,...,1.609200,1.589200,1.5692,1.549933,1.530667,1.5114,1.492833,1.474267,1.4557,1.4557
4808,Korea,Freight,Truck,Truck,BEV,Electricity,intensity,MJ/vkm,0.4559,0.453600,...,0.433633,0.431467,0.4293,0.427167,0.425033,0.4229,0.420800,0.418700,0.4166,0.4166

In [33]:
T=15
dfSub["rate_2020_2030"] = 1 - (dfSub['2035']/dfSub['2020'])**(1/T)
out = dfSub[["UCD_sector","size.class","UCD_technology","UCD_fuel","rate_2020_2030"]]
out

     UCD_sector size.class UCD_technology     UCD_fuel  rate_2020_2030
2303    Freight      Truck        Liquids      Liquids        0.002503
2304    Freight      Truck             NG  Natural Gas        0.002499
4808    Freight      Truck            BEV  Electricity        0.001002